### ISSUE TITLE
Add XSL PHP extension

### ISSUE THREAD

**Issue by vijaycs85** [smmccabe/docker#22]
Static analyzer like [PHPQA](https://github.com/EdgedesignCZ/phpqa) (and so [Drupal PHPQA](https://github.com/vijaycs85/drupal-phpqa)) requires [XSL](https://www.php.net/manual/en/book.xsl.php) extension.

**Comment by smmccabe** [comment]
XSL not XLS

**Comment by vijaycs85** [comment]
oops, my bad.
